//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Postwomen.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Postwomen.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings Disabled.
        /// </summary>
        internal static string advancedsettingsdisabled {
            get {
                return ResourceManager.GetString("advancedsettingsdisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings Enabled.
        /// </summary>
        internal static string advancedsettingsenabled {
            get {
                return ResourceManager.GetString("advancedsettingsenabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert me if response is:.
        /// </summary>
        internal static string alertmeifresponseis {
            get {
                return ResourceManager.GetString("alertmeifresponseis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application closing... Please restart after exit..
        /// </summary>
        internal static string appclosing {
            get {
                return ResourceManager.GetString("appclosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaible Actions.
        /// </summary>
        internal static string avaibleactions {
            get {
                return ResourceManager.GetString("avaibleactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Type:.
        /// </summary>
        internal static string calltype {
            get {
                return ResourceManager.GetString("calltype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Card Name.
        /// </summary>
        internal static string cardname {
            get {
                return ResourceManager.GetString("cardname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Cycle (as seconds).
        /// </summary>
        internal static string checkcycle {
            get {
                return ResourceManager.GetString("checkcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create new one.
        /// </summary>
        internal static string clicktocreatenewone {
            get {
                return ResourceManager.GetString("clicktocreatenewone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Card.
        /// </summary>
        internal static string copycard {
            get {
                return ResourceManager.GetString("copycard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Style.
        /// </summary>
        internal static string darkstyle {
            get {
                return ResourceManager.GetString("darkstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        internal static string dateandtime {
            get {
                return ResourceManager.GetString("dateandtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is 100 sec.
        /// </summary>
        internal static string defaultis100sec {
            get {
                return ResourceManager.GetString("defaultis100sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is 5000.
        /// </summary>
        internal static string defaultis5000 {
            get {
                return ResourceManager.GetString("defaultis5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is 600 sec, min 30.
        /// </summary>
        internal static string defaultis600sec {
            get {
                return ResourceManager.GetString("defaultis600sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay After Notification:.
        /// </summary>
        internal static string delayafternotification {
            get {
                return ResourceManager.GetString("delayafternotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting card.
        /// </summary>
        internal static string deletingcard {
            get {
                return ResourceManager.GetString("deletingcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this card?.
        /// </summary>
        internal static string deletingcardask {
            get {
                return ResourceManager.GetString("deletingcardask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card.
        /// </summary>
        internal static string editcard {
            get {
                return ResourceManager.GetString("editcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Fields with * are required.).
        /// </summary>
        internal static string fieldsarerequired {
            get {
                return ResourceManager.GetString("fieldsarerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not reachable!.
        /// </summary>
        internal static string isnotreachable {
            get {
                return ResourceManager.GetString("isnotreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string logs {
            get {
                return ResourceManager.GetString("logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Log Count.
        /// </summary>
        internal static string maxlogcount {
            get {
                return ResourceManager.GetString("maxlogcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe no internet browser avaible on this device. Ex: .
        /// </summary>
        internal static string maybenointernet {
            get {
                return ResourceManager.GetString("maybenointernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Card.
        /// </summary>
        internal static string newcard {
            get {
                return ResourceManager.GetString("newcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server card found..
        /// </summary>
        internal static string noservercardfound {
            get {
                return ResourceManager.GetString("noservercardfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open browser.
        /// </summary>
        internal static string openbrowser {
            get {
                return ResourceManager.GetString("openbrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wanna go to.
        /// </summary>
        internal static string openbrowserask {
            get {
                return ResourceManager.GetString("openbrowserask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Result.
        /// </summary>
        internal static string operationresult {
            get {
                return ResourceManager.GetString("operationresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name for your card.
        /// </summary>
        internal static string pleaseenternameforcard {
            get {
                return ResourceManager.GetString("pleaseenternameforcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter URL or IP for your card.
        /// </summary>
        internal static string pleaseenterurlforcard {
            get {
                return ResourceManager.GetString("pleaseenterurlforcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol:.
        /// </summary>
        internal static string protocol {
            get {
                return ResourceManager.GetString("protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Call.
        /// </summary>
        internal static string readytocall {
            get {
                return ResourceManager.GetString("readytocall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        internal static string refreshing {
            get {
                return ResourceManager.GetString("refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Remote URL/IP.
        /// </summary>
        internal static string remoteurlorip {
            get {
                return ResourceManager.GetString("remoteurlorip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Database.
        /// </summary>
        internal static string resetdatabase {
            get {
                return ResourceManager.GetString("resetdatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really want to reset your database?.
        /// </summary>
        internal static string resetdatabaseask {
            get {
                return ResourceManager.GetString("resetdatabaseask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Logs.
        /// </summary>
        internal static string resetlogs {
            get {
                return ResourceManager.GetString("resetlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is card logs will be deleted?.
        /// </summary>
        internal static string resetlogsask {
            get {
                return ResourceManager.GetString("resetlogsask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Server Cards.
        /// </summary>
        internal static string resetservercards {
            get {
                return ResourceManager.GetString("resetservercards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is server cards will be deleted?.
        /// </summary>
        internal static string resetservercardsask {
            get {
                return ResourceManager.GetString("resetservercardsask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Language.
        /// </summary>
        internal static string selectedlanguage {
            get {
                return ResourceManager.GetString("selectedlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Send notifications on changes&apos; disabled.
        /// </summary>
        internal static string sendnotifonchangesdisabled {
            get {
                return ResourceManager.GetString("sendnotifonchangesdisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Send notifications on changes&apos; enabled.
        /// </summary>
        internal static string sendnotifonchangesenabled {
            get {
                return ResourceManager.GetString("sendnotifonchangesenabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers are not reachable!.
        /// </summary>
        internal static string serversarenotreachable {
            get {
                return ResourceManager.GetString("serversarenotreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set body:.
        /// </summary>
        internal static string setbody {
            get {
                return ResourceManager.GetString("setbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set headers:.
        /// </summary>
        internal static string setheaders {
            get {
                return ResourceManager.GetString("setheaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set port for your card. Default is 443.
        /// </summary>
        internal static string setportforyourcard {
            get {
                return ResourceManager.GetString("setportforyourcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Time scheduled checks&apos; disabled.
        /// </summary>
        internal static string timechecksdisabled {
            get {
                return ResourceManager.GetString("timechecksdisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Time scheduled checks&apos; enabled.
        /// </summary>
        internal static string timechecksenabled {
            get {
                return ResourceManager.GetString("timechecksenabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add a description for your card.
        /// </summary>
        internal static string youcanadddescriptionforcard {
            get {
                return ResourceManager.GetString("youcanadddescriptionforcard", resourceCulture);
            }
        }
    }
}
